### PR TITLE
Added tokensEither

### PR DESCRIPTION
**Pull request by mitchellwrosen**
Not sure if you're interested in this function, but it's here if you want it :)

The implementation is a bit yucky - I tried to reuse the current implementation, and just sprinkled some MonadError calls throughout, then made a bogus Identity newtype with a 'throwError' that just calls 'throw'.

### CODE REVIEW

**Comment by feuerbach** [comment]
I'm afraid I agree with your assessment of the implementation :-)

I'd rather you implemented this with `catch` and `unsafePerformIO`. (There's also the `spoon` package, but it's not worth an extra dependency.)

**Comment by mitchellwrosen** [comment]
:) How about now?

**Comment by feuerbach** [comment]
1. Please record a separate clean commit instead of undoing the previous one
2. We actually only need to force the spine of the list. This solves all the problems associated with deepseq (orphan instance, extra constraint on the token type, extra dep) and is also more efficient (avoids doing extra work).
The list spine can be forced by evaluating `foldr (const id) () list`.

**Comment by feuerbach** [comment]
FYI, I just wrote an article with some more detail about forcing lists: https://ro-che.info/articles/2015-05-28-force-list

**Comment by mitchellwrosen** [comment]
Neat! I think you mean `forceElements` though, no? We have to seq the `L`

**Comment by mitchellwrosen** [comment]
Updated.

**Comment by feuerbach** [comment]
Much better! Still there are issues:

1. The build failed
3. The `fromJust . fromException` bit is wrong; it will fail with `Maybe.fromJust: Nothing` is any other exception is thrown. You should just remove that whole line, and `try` will take care of catching only the right exception.
3. There are still many unrelated changes in your [commit](https://github.com/mitchellwrosen/lexer-applicative/commit/330550ca06425dc4897e96a9b09e15a7472cad1d) (mostly whitespace). Make sure the patch contains only the change you actually want and claim to make.
3. Likewise with tests. You don't have to modify any existing code there. Simply add another test that would specifically test that `tokensEither` works. Since it is based on `tokens`, there's no need to do exhaustive checking — one successful and one failing example should suffice, so that we know we're catching the exception properly.

**Comment by mitchellwrosen** [comment]
Hm, tests passed on my machine. Must be a GHC version thing. I'll get to the other issues hopefully tonight. Apologies about whitespace changes, some of that was knee-jerk reaction to un-aligned lines, and some was my editor deleting trailing whitespace on change.

**Comment by mitchellwrosen** [comment]
Updated. It wasn't a GHC version issue, I'm just an idiot and pushed broken code.

**Comment by feuerbach** [comment]
Merged, thanks.

**Pull request closed without merging**
